### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by jaumard** [leeroybrun/sails-util-mvcsloader#1]
It look great but I didn't manage how it can work because the initialise method do nothing and other methods are not called ? Can you explain a little bit ?

**Comment by leeroybrun** [comment]
Hi,

This is still experimental yet.
It should work, but I have not had enough time to test it a lot.

For now, you can install it in your sails folder (`npm install sails-hook-hookloader`).

Then use it like this in your hook's `index.js` :

``` javascript
module.exports = function(sails) {
  var hookLoader = require('sails-hook-hookloader')(sails);

  return {
    initialize: function(cb) {
      hookLoader.injectAll({
        controllers: __dirname+'/controllers', // Path to your hook's controllers
        models: __dirname+'/models' // Path to your hook's models
      }, function(err) {
        return cb();
      });
    }
  }
}
```

**Comment by jaumard** [comment]
Thanks ! I will give it a try and let you know :) it's a very interesting feature that I will need in the futur. Would be interesting to have some views too under hooks.

**Comment by leeroybrun** [comment]
Great! Let me know what do you think about it :-)

I plan to continue development of this as soon as I can.
The goal is to be able to load everything (services, views, etc).

**Comment by jaumard** [comment]
I make a fork on this project :) https://github.com/jaumard/sails-hook-hookloader
Love the way you implement this ! So far no problem found just miss some features :) 

I change your extends on controllers and models, like this you can first use a controller hook on your sails project and override controller function on your own controller with same name (same for models and services) not sure I'm clear sorry for my english.
I implement a loader for hook services ;).

Look at it when you have time and tell me if you want me to make a pull request.
