### ISSUE TITLE
Models are being overridden - missing methods

### ISSUE THREAD

**Issue by Ehesp** [leeroybrun/sails-util-mvcsloader#10]
This lib is overriding the `sails.models`, not extending. This means models lose either the ORM methods or socket methods depending on your setup.

I think https://github.com/leeroybrun/sails-util-mvcsloader/blob/master/libs/models.js#L30 is the culprit. It needs to be assigned instead of directly doing `sails.models =`.

**Comment by leeroybrun** [comment]
Thanks for pointing this.

Unfortunately I don't have the time to fix this for now, but if you send me a pull request, I will merge it.

**Comment by budmitr** [comment]
Fixed in #12 
@leeroybrun can you please accept merge?

**Comment by OscarMeier** [comment]
@leeroybrun Could you please merge the pull request and publish the new version on npm?

**Comment by leeroybrun** [comment]
@Elbarto9 unfortunately as explained in #9, I need someone to check if the fix is also working with older versions of Sails before I can merge.

**Comment by Ehesp** [comment]
@leeroybrun how far/what version do you want it testing back to?

**Comment by leeroybrun** [comment]
The change on the models seems to come from v0.12.2, so this could be good to test it with v0.12. No need to try with earlier versions.

**Comment by leeroybrun** [comment]
I finally merged this, and if it does not works with older Sails versions, people can stay with v0.3.2. Will push  v0.4.0 to NPM in a few minutes.
