### ISSUE TITLE
Policies not working

### ISSUE THREAD

**Issue by Pierre-Gilles** [leeroybrun/sails-util-mvcsloader#3]
Hi,

I'm using your awesome module in my project Gladys ( https://github.com/GladysProject/Gladys ).

Everything works fine, but seems that requests are not passing threw created policies. 

In the main app, I've set a default policy rule ( `'*': false` ). And seems that this rule override all the policies rules defined in a hooks. 

Maybe I'm doing something wrong !

( If you want to see what my hook look like, here is it : https://github.com/GladysProject/Gladys/tree/master/api/hooks/example ) 

Many thanks for your reply and for the module :)

**Comment by jaumard** [comment]
Hi, :)

Happy to hear anyone that use this module ! In fact during sails lift, this module merge everything that is on your module. But everything you configure in your sails projet will override your hook configuration.

In your example you have ( '_': false ) under sails and ( '_': ["test"] ) under your hook so when the module merge both they only left ( '*': false ) :/ 

This module give the possibilities to provide config/model/controller ect... that can be override on the project that use the hook (with this module).

If you want to call your test and block access to route you have to create a new policy that do same as \* : false and configure '*' : ["dontAllow"]
When merge become you will have ["doncAllow", "test"] at the end :) 

It's more clear ?

**Comment by Pierre-Gilles** [comment]
Ok, that's very clear :)

But in my case, if I have understood, if I change my `config/policies.js` in my hooks with the following code : 

```
module.exports = {
    Example : ['test']
};
```

I still get a forbidden error, it does not pass threw the test policies when I try to access `/example/test` ! 
It's because `'*': false` in my sails app override everything ?

If yes, I will create a policies for '*' : false like you said, very nice idea.

Thank you very much for your time,

**Comment by jaumard** [comment]
I just make a small test and something is wrong with our module... I have a project that work great but on a fresh sails project configuration was not load properly... I will try to fix this quickly.
The problem is here https://github.com/leeroybrun/sails-util-mvcsloader/blob/master/libs/config.js on my working project sails-build-dictionary give me 

``` javascript
{
     policies : {"HomeController" : ["test"]}
}
```

But with a fresh sails project it give me 

``` javascript
{
   "HomeController" : ["test"]
} 
```

And that's the problem... Config are not merge correctly 
You can put a breakpoint and see if you have same problem.

**Comment by jaumard** [comment]
@leeroybrun do you have an idea for this ?

**Comment by Pierre-Gilles** [comment]
Do you finally find what's going on ? 

Is the problem about the aggregate function which returns a wrong configs var, or during the merge by lodash (_.merge) ? 

```
buildDictionary.aggregate({
        dirname: dir,
        exclude: ['locales', 'local.js', 'local.json', 'local.coffee', 'local.litcoffee'],
        excludeDirs: /(locales|env)$/,
        filter: /(.+)\.(js|json|coffee|litcoffee)$/,
        identity: false
    }, function (err, configs) {
        sails.config = _.merge(configs, sails.config, function (a, b) {
            if (_.isArray(a)) {
                return a.concat(b);
            }
        });
    });
```

I hope we will find the bug as soon as possible it's a little bit blocking developer in the development of module for my Gladys project :D

**Comment by jaumard** [comment]
I know what is the problem but I don't know why it occurred :/ 
In fact the aggregate function return a wrong config object, it merge all content of config instead of create an object with config file inside. I have project who it's working great and a fresh project don't work, but dependencies are equals...

As I said in my previous post normally the aggregate function have to return this : 

``` javascript
{
     policies : {"HomeController" : ["test"]}
}
```

But with return this : 

``` javascript
{
   "HomeController" : ["test"] //content of policies.js
} 
```

So when I merge config, there are merge with the sails object instead of the sails.config object... The hook config is ignored

**Comment by Pierre-Gilles** [comment]
Maybe you can encapsulate the returned value : 

```
{
   "HomeController" : ["test"] //content of policies.js
} 
```

Like that : 

```
configs = { policies : configs }; 
```

?

( I agree that's a dirty fix, maybe we should find what's going on )

**Comment by jaumard** [comment]
That's not possible cause config are not only policies ^^ in you case yes but I use this module in sails-hook-passport and it load policies.js, http.js, routes.js.... So if I do what you said other modules how load more than policies will not work... 
Sorry for the inconvenience. I will search a way to replace build-dictionary maybe it will work better

**Comment by Pierre-Gilles** [comment]
Ok I understand! I need routes.js too so that's not a solution even for me.

The weirdest thing is that it work for you on an old project!

Thanks for your quick reply,

**Comment by jaumard** [comment]
Can you test this ? Edit our libs/config.js file and replace the build-dictionary with this 

``` javascript
var configs = require('include-all')({
    dirname     : dir,
    exclude     : ['locales', 'local.js', 'local.json', 'local.coffee', 'local.litcoffee'],
    filter      : /(.+)\.(js|json|coffee|litcoffee)$/,
    excludeDirs : /(locales|env)$/,
  });
sails.config = _.merge(configs, sails.config, function (a, b) {
    if (_.isArray(a)) {
      return a.concat(b);
    }
  });
```

For me now it's working correctly, let me know if for you it's the same. If yes I will replace all build-dictionary with this

**Comment by Pierre-Gilles** [comment]
Yes it's working as expected ! :) Thank you so much !

**Comment by Pierre-Gilles** [comment]
I hope their will be no side effect with this change, but for now seems thats everything is correctly injected.

**Comment by jaumard** [comment]
Normally there no side effect cause build-dictionary already use include-all ^^ let me replace all build-dictionary and make some test and I put an update.

**Comment by Pierre-Gilles** [comment]
Nice job, thank you very much :)

**Comment by jaumard** [comment]
Thanks to you for reporting this :) sails-util-mvcsloader@0.2.4 is online let me know if you have problems

**Comment by Pierre-Gilles** [comment]
Just updated Gladys, it now work perfectly ! Thank for your help :)

**Comment by jaumard** [comment]
Hi,

I just found why this problem append !!! My example is wrong ! Normally a config file in sails is like this : 

module.export.myconfig = {}

but in the example it's 

module.export = {}

So I have to correct the example and restaure the loader like before cause config file have to be the same as sails.

**Comment by Pierre-Gilles** [comment]
Yes you are right! Perfect, tell me on this feed when the change is made, I will update Gladys in consequence :)

**Comment by jaumard** [comment]
It's under the 0.3.0 version :) normally everything is ok or let me know.
