### ISSUE TITLE
Models broken with sails since 0.12.2

### ISSUE THREAD

**Issue by dilame** [leeroybrun/sails-util-mvcsloader#9]
It not works with sails since 0.12.2.
No errors, no warnings, models just not load.

**Comment by Ehesp** [comment]
Probably the issue: https://github.com/leeroybrun/sails-util-mvcsloader/issues/10

**Comment by Pierre-Gilles** [comment]
+1 I have the same problem in [Gladys](https://github.com/GladysProject/Gladys)

**Comment by Ehesp** [comment]
This should technically be an easy one to fix, just need to run some checks & tests over it.

**Comment by budmitr** [comment]
Fixed in #12 
@leeroybrun can you please accept merge?

**Comment by leeroybrun** [comment]
Thanks for your pull request.

Will it still works with previous versions of Sails?
I'm not using it (Sails) anymore, so I don't have any apps to test this.

**Comment by budmitr** [comment]
@leeroybrun, actually, I did not check :)
I'll get back with tests results asap

**Comment by budmitr** [comment]
sorry folks, suddenly I got a lot of other workload and can't get back to this
if someone can check this codechange on other versions of sails, please do

**Comment by dilame** [comment]
@leeroybrun why you not use sails anymore? Had you found another nice framework?

**Comment by leeroybrun** [comment]
@dilame I'm now using [Feathers](http://feathersjs.com/). It's not the same kind of framework, Sails is a lot more complete but the structure and working of your app is imposed. I found myself limited by this (this is why I started working on `sails-util-mvcsloader`) and this is why I left to use Feathers instead as it let me be totally free.

**Comment by leeroybrun** [comment]
Fixed in #12. Thanks @budmitr for your work.
